<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<center><h1>Disco</h1></center>
            <center><img src="<?php echo base_url(); ?>/public/IMG/Galaxy-1.jpg" width="450" height="300"></center>
            <p class="text-justify">El <b>disco</b> se compone principalmente de estrellas jóvenes de población I. Es la parte de la galaxia que más gas contiene y es en él donde aún se dan procesos de formación estelar. Lo más característico del disco son los brazos espirales, que son cuatro: dos brazos principales Escudo-Centauro y Perseo, así como dos secundarios —Sagitario y Escuadra— (en vez de cuatro brazos similares entre sí, como se pensaba antes).</p>
            <center><img src="<?php echo base_url(); ?>/public/IMG/Galaxy-3.jpg" width="450" height="300"></center>
            <p class="text-justify">Recientemente un grupo de astrónomos anunció el descubrimiento de un nuevo brazo espiral en nuestra galaxia, concretamente un enorme fragmento hasta ahora desconocido;8​ se cree que el nuevo brazo espiral es, en realidad, el tramo final y más distante del brazo de Escudo-Centauro, una de las dos ramas principales.9​ De confirmarse, los autores habrán demostrado que la Vía Láctea posee una sorprendente simetría en sus formas, ya que este nuevo brazo sería la contraparte simétrica del de Perseo.10​ Hay que tener en cuenta que nuestra posición en la Vía Láctea —a mitad de camino entre su centro y su borde y prácticamente en el plano galáctico— dificulta en gran medida el estudio de la estructura espiral de nuestra galaxia.</p>
            <center><img src="<?php echo base_url(); ?>/public/IMG/Partes.jpg" width="450" height="300"></center>
            <p class="text-justify">Nuestro Sistema Solar se encuentra en el brazo Orión o Local, que forma parte del brazo espiral de Sagitario, de allí su nombre de «Local». Estas formaciones son regiones densas donde se compacta el gas y se da la formación de estrellas. Los brazos son, en realidad, ondas de densidad que se desplazan independientemente de las estrellas contenidas en la galaxia. El brillo de los brazos es mayor que el resto de las zonas, porque es allí donde se encuentran las gigantes azules (estrellas de tipo O, B), que son las únicas que pueden ionizar grandes extensiones de gas. Estas estrellas de corta vida nacen y mueren en el brazo espiral, convirtiéndose así en excelentes marcadores de su posición. Otros trazadores de los brazos espirales son las regiones HII (nubes de hidrógeno ionizado), originadas precisamente por esos gigantes azules. Estas nubes vuelven a emitir, en el rango de la luz visible, la energía captada en el ultravioleta o en otras frecuencias más cortas. Son altamente energéticas, pues han sido ionizadas por las potentes gigantes azules, que barren extensas áreas con sus vientos estelares.</p>
            <center><img src="<?php echo base_url(); ?>/public/IMG/Galaxy-4.jpg" width="450" height="300"></center>
            <p class="text-justify">Las estrellas de vida más larga como el Sol ya no sirven como marcadores, ya que tienen tiempo a lo largo de su vida de entrar y salir repetidas veces en los diferentes brazos espirales de la galaxia. Estas estrellas pueden encontrarse también fuera de los brazos.</p>
            <p class="text-justify">Así como la galaxia se compone de dos partes según su grosor, halo y disco, el disco también: disco delgado y disco grueso. Se cree que el disco grueso es el remanente de un segundo proceso de colapso y aplanamiento de la galaxia. Del mismo modo que el halo es el remanente del colapso inicial, el disco grueso lo sería de una segunda fase de colapso.</p>
            <p class="text-justify">El disco está unido al bulbo galáctico por una barra de radio 3,9 kiloparsecs,​ en cuyo interior a su vez puede existir una barra menor (algo que ocurre en bastantes otras galaxias espirales barradas). Hay además elevada formación estelar en al menos uno de sus extremos</p>
            <center><img src="<?php echo base_url(); ?>/public/IMG/Galaxy-5.jpg" width="450" height="300"></center>
            <p class="text-justify">La barra mayor está ceñida a su vez por un anillo de 5 kiloparsecs de radio, que concentra, además de una gran cantidad del hidrógeno molecular de la galaxia, una gran actividad de formación estelar. Dicho anillo es la estructura más notable de nuestra galaxia, y visto desde otras galaxias exteriores sería su zona más prominente.14​ De este anillo emergen los brazos espirales.</p>
            <p class="text-justify">Recientemente se ha sugerido que la Galaxia Elíptica Enana de Sagitario puede ser la responsable de la estructura espiral de nuestra galaxia, ayudando a dar forma a los brazos espirales, modelando la barra central, y distorsionando sus regiones exteriores.</p>
            <p class="text-justify">Se cree que posiblemente nuestra galaxia tiene entre 4000 millones y 8000 millones de masas solares de hidrógeno neutro, además de la mitad de esa masa en la forma de hidrógeno molecular. Mientras que el primero llega más allá del espacio ocupado por las estrellas —pero la región central apenas tiene gas en esa forma—, gran parte del segundo está concentrado en el anillo mencionado antes, y —excepto en la región más interna de la Vía Láctea— la densidad de hidrógeno molecular en la región central de la galaxia también es baja.</p>
            <center><img src="<?php echo base_url(); ?>/public/IMG/Galaxy-2.jpg" width="450" height="300"></center>
            <p class="text-justify">Inicialmente se pensó que la tasa de formación estelar de nuestra galaxia sería de hasta cinco masas solares por año; sin embargo, estudios más recientes realizados con ayuda del telescopio de infrarrojos Spitzer sugieren una mucho menor, de apenas una masa solar por año,17​ y otro también sugiere que nuestra galaxia junto a la de Andrómeda se halla en lo que en el diagrama de color-magnitud para galaxias se conoce cómo el valle verde: una zona intermedia entre la secuencia roja (galaxias que no forman estrellas, muchas de ellas galaxias elípticas) y la nube azul (galaxias que forman estrellas a gran ritmo, muchas de ellas galaxias espirales), caracterizada por una progresiva disminución de la formación estelar al irse acabando el gas a partir del cual nacen las estrellas, calculándose que esta acabará dentro de 5000 millones de años, incluso contando con el aumento de la formación estelar que llevará su colisión futura con la Galaxia de Andrómeda.18​19​ Esto ha sido reforzado por estudios más recientes que muestran que, sin incluir sus brazos espirales, la Vía Láctea tiene un color más rojizo que otras galaxias espirales similares, lo que implica que su actividad de formación de estrellas está relativamente próxima a acabar;20​ de hecho es solo algo más azulada que las galaxias más azules de la secuencia roja y está entre las más brillantes y rojas de las galaxias que aún siguen formando estrellas.</p>
            <p class="text-justify">Estudios recientes muestran que nuestra galaxia es atípica por no haber sufrido en los últimos 10 000 millones de años ninguna fusión importante con otra, sobre la base de sus bajos momento angular, metalicidad, tamaño, y número de estrellas, habiendo formado estrellas de manera bastante constante y tenido una evolución relativamente tranquila, a diferencia de lo que ha sucedido con numerosas otras galaxias espirales cómo Andrómeda, las cuales han adquirido su tamaño y masa actuales debido a la absorción de numerosas galaxias menores. Ello también implica que una colisión entre dos galaxias espirales no tiene porqué crear siempre una galaxia elíptica, sino que puede dar lugar a una galaxia espiral mayor.</p>
            <p class="text-justify">Esta parte de la Vía Láctea tiene una masa de 60 000 millones de masas solares en forma de estrellas y una luminosidad de entre 15 000 y 20 000 millones de veces la del Sol.</p>
            <center><img src="<?php echo base_url(); ?>/public/IMG/Disco.jpg" width="450" height="300"></center>
		</div>	
	</div>
</div>