<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<center><h1>Formación</h1></center>
			<center><img src="<?php echo base_url(); ?>/public/IMG/Galaxy-5.jpg" width="450" height="300"></center>
			<p class="text-justify">La Vía Láctea comenzó como una o varias pequeñas regiones de sobredensidad en la distribución másica del universo poco después del Big Bang. Algunas de estas regiones eran las semillas de los cúmulos globulares, en los que perduran las más antiguas estrellas que formaron la galaxia. Estas estrellas y cúmulos constituyen en la actualidad el halo estelar de la Vía Láctea. Tras unos pocos miles de millones de años después de las primeras estrellas, la masa de la galaxia era lo suficientemente grande como para que diera vueltas con relativa rapidez, lo que, debido a la conservación del momento angular, condujo a que el medio gaseoso interestelar colapsase de una forma más o menos esférica a un disco plano. Por lo tanto, las siguientes generaciones de estrellas se formaron en este disco espiral. La mayoría de las estrellas jóvenes, incluido el Sol, se encuentran en este disco.</p>
			<p class="text-justify">Desde el momento en que comenzaron a formarse las primeras estrellas, la Vía Láctea ha crecido mediante fusiones de galaxias (sobre todo al principio) y la acreción de gas del halo galáctico.26​ La Vía Láctea está en la actualidad aumentando su masa con sus dos más cercanas galaxias satélite, la Gran Nube de Magallanes y la Pequeña Nube de Magallanes, mediante la corriente de Magallanes. La acreción directa de gas se constata en nubes de alta velocidad como la nube de Smith.27​28​ Sin embargo, propiedad de la Vía Láctea como la masa estelar, el momento angular y la metalicidad de sus regiones más externas sugieren que no ha sufrido fusiones con grandes galaxias en los últimos mil millones de años. Esta ausencia de grandes fusiones recientes es inusual entre galaxias espirales similares; su vecina, la galaxia de Andrómeda, parece tener una historia más típica con fusiones más recientes con galaxias relativamente grandes.</p>
			<p class="text-justify">Según recientes estudios, la Vía Láctea así como Andrómeda se encuentran en lo que se conoce como valle verde dentro del diagrama color-magnitud, una región poblada por galaxias en transición de la nube azul (galaxias con formación activa de nuevas estrellas) a la secuencia roja (galaxias que carecen de formación estelar). La formación de estrellas en las galaxias del valle verde va desacelerando a medida que se quedan sin gas en el medio interestelar. En simulaciones galácticas con propiedades semejantes, esta formación habrá desaparecido en unos cinco mil millones de años, incluso teniendo en cuenta el incremento a corto plazo en la tasa de formación por la colisión entre la Vía Láctea y Andrómeda.31​ De hecho, las medidas en otras galaxias similares a la Vía Láctea sugieren que esta está entre las galaxias espirales más rojas y brillantes que todavía forman nuevas estrellas y que es solo ligeramente más azul que las galaxias más azules de la secuencia roja.</p>
			<center><img src="<?php echo base_url(); ?>/public/IMG/Galaxy-1.jpg" width="450" height="300"></center>
			<center><h2>Edad e historia cosmológica</h2></center>
			<p class="text-justify">Los cúmulos globulares se encuentran entre los objetos más antiguos de la Vía Láctea, lo que establece un límite inferior a la edad de la Vía Láctea. Las edades de las estrellas individuales en la Vía Láctea pueden estimarse midiendo la abundancia de elementos radiactivos de larga vida como el torio-232 y el uranio-238, y luego comparando los resultados con las estimaciones de su abundancia original, una técnica llamada nucleocosmocronología. Esto resulta en valores de aproximadamente 12,5 ± 3 mil millones de años para la CS 31082-00134​ y 13,8 ± 4 mil millones de años para la BD +17° 3248.35​ Una vez que se forma una enana blanca, esta comienza a sufrir un enfriamiento radiativo y la temperatura de la superficie desciende de manera constante. Midiendo las temperaturas de la más fría de estas enanas blancas y comparándolas con su temperatura inicial esperada, se puede hacer una estimación de la edad. Con esta técnica, la edad del cúmulo globular M4 se ha estimado en 12,7 ± 0,7 mil millones de años. Las estimaciones de edad del más antiguo de estos grupos dan un valor estimado de 12 600 millones de años, y un límite superior de confianza del 95% de 16 000 millones de años.</p>
			<p class="text-justify">Se han encontrado varias estrellas individuales en el halo de la Vía Láctea con edades medidas muy cercanas a los 13.80 mil millones de años de edad del Universo. En 2007, se estimó que una estrella en el halo galáctico, HE 1523-0901, tenía unos 13 200 millones de años. Como el objeto más antiguo conocido en la Vía Láctea en ese momento, esta medición puso un límite inferior a la edad de la Vía Láctea.37​ Esta estimación se realizó utilizando el Ultraviolet and Visual Echelle Spectrograph del Very Large Telescope para medir las fuerzas relativas de las líneas espectrales causadas por la presencia de torio y otros elementos creados por el proceso R. La resistencia de las líneas produce abundancia de diferentes isótopos elementales, de los cuales se puede obtener una estimación de la edad de la estrella utilizando la nucleocosmocronología.37​ Otra estrella, HD 140283, tiene 14,5 ± 0,7 mil millones de años de edad.</p>
			<p class="text-justify">También se ha estimado la edad de las estrellas en el disco delgado galáctico utilizando la nucleocosmocronología. Las mediciones de las estrellas de disco delgado arrojan una estimación de que el disco delgado se formó hace 8,8 ± 1,7 mil millones de años. Estas mediciones sugieren que hubo un período de casi 5 mil millones de años entre la formación del halo galáctico y el disco delgado.40​ Análisis recientes de las firmas químicas de miles de estrellas sugieren que la formación estelar podría haber caído en un orden de magnitud en el momento de la formación del disco, hace 10 a 8 mil millones de años, cuando el gas interestelar estaba demasiado caliente para formar nuevas estrellas a la misma velocidad que antes.</p>
			<p class="text-justify">Las galaxias satelitales que rodean la Vía Láctea no están distribuidas al azar, sino que parecen ser el resultado de la desintegración de un sistema más grande en el que se produjo una estructura anular de 500 000 años luz de diámetro y de 50 000 años luz de ancho.42​ Encuentros cercanos entre las galaxias, como el que se espera que tenga lugar dentro de los próximos 4000 millones de años con la galaxia de Andrómeda, arrancan colas gigantescas de gas, que, con el paso del tiempo, pueden fusionarse y formar galaxias enanas en forma de anillos y con un ángulo arbitrario respecto al disco principal.</p>
			<center><img src="<?php echo base_url(); ?>/public/IMG/Bulbo.jpg" width="450" height="300"></center>
			<p class="text-justify">En noviembre de 2018, los astrónomos anunciaron el descubrimiento de una de las estrellas más antiguas del universo. Con una antigüedad aproximada de 13 500 millones de años, 2MASS J18082002-5104378 es una pequeña estrella ultra pobre en metales (UMP) compuesta casi en su totalidad por materiales liberados por el Big Bang, y es posiblemente una de las primeras estrellas. El descubrimiento de la estrella en la Vía Láctea sugiere que la galaxia puede ser por lo menos tres mil millones de años más vieja de lo que se pensaba con anterioridad.</p>
		</div>	
	</div>
</div>