<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<center><h1>Vía Láctea</h1></center>
			<center><img src="<?php echo base_url(); ?>/public/IMG/Via-Lactea.jpg" width="450" height="300"></center>
			<p class="text-justify">La <b>Vía Láctea</b> (en griego: γαλαξίας κύκλος -galaxías kýklos- "círculo lácteo") es una galaxia espiral donde se encuentra el sistema solar y a su vez se encuentra la Tierra. Según las observaciones, posee una masa de 1012 masas solares y es una espiral barrada. Su diámetro medio se estima en unos 200 000 años luz, (1,89×1018 kilómetros) o 12 648 millones de unidades astronómicas. En mayo de 2018, un equipo de investigadores del Instituto Astrofísico de Canarias y el National Astronomical Observatories de Pekín (NAOC) publicaron nuevas observaciones que amplían el diámetro hasta 200 000 años luz. Se calcula que contiene entre 200 000 y 400 000 millones de estrellas. La distancia desde el Sol hasta el centro de la galaxia es de alrededor de 25 766 años luz (7900 pc), es decir, el 52 % del radio total galáctico. La Vía Láctea forma parte de un conjunto de unas cuarenta galaxias llamado Grupo Local, y es la segunda más grande y brillante tras la galaxia de Andrómeda, aunque puede ser la más masiva, como muestra un estudio reciente.</p>
			<center><img src="<?php echo base_url(); ?>/public/IMG/Observatorio-Paranal.jpg" width="450" height="300" title="Observatorio Paranal"></center>
			<p class="text-justify">El nombre Vía Láctea proviene de la mitología latina, y esta de la griega que significa en latín camino de leche. Esa es, en efecto, la apariencia de la tenue banda de luz que atraviesa el firmamento terrestre, y así lo afirma la mitología griega, explicando que se trata de leche derramada del pecho de la diosa Hera (Juno para los romanos). Rubens representa la leyenda en su obra El nacimiento de la Vía Láctea. Sin embargo, ya en la Antigua Grecia, el astrónomo Demócrito (460-370 a. C.) sugirió que aquel haz blanco en el cielo era en realidad un conglomerado de muchísimas estrellas demasiado tenues individualmente como para ser reconocidas a simple vista. Su idea, no obstante, no tuvo respaldo hasta 1609, cuando el astrónomo italiano Galileo Galilei hace uso del telescopio y constata que Demócrito estaba en lo cierto, ya que a donde quiera que mirase, aquel se encontraba lleno de estrellas.</p>
			<center><img src="<?php echo base_url(); ?>/public/IMG/Galileo Galile.jpg" width="450" height="300" title="Galileo Galile"></center>
			<br>
		</div>	
	</div>
</div>